name: Build and publish docker images

on:
  push:
    branches:
      - master
env:
  DOCKER_REGISTRY: 'ghcr.io'
  DOCKER_TAG_MAJOR: '2.0'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build and publish
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
            
    - name: Get repository variable in lowercase
      run: echo "REPOSITORY=$(echo $GITHUB_REPOSITORY | tr '[A-Z]' '[a-z]')" >> $GITHUB_ENV
      
    - name: Get branch name
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

    - name: Setting docker tag prefix
      if: "!contains(github.ref, 'master')"
      run: |
          echo "DOCKER_TAG_PREFIX_EXCEPT_MAIN=${{ env.BRANCH_NAME }}-" >> $GITHUB_ENV
          echo "DOCKER_TAG_POSTFIX_EXCEPT_MAIN=-${{ env.BRANCH_NAME }}" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build for arm64 and push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: BUILD_FOR=arm64
        tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPOSITORY }}:${{env.DOCKER_TAG_MAJOR }}.${{ github.run_number }}${{ env.DOCKER_TAG_POSTFIX_EXCEPT_MAIN }}-arm64
            ${{ env.DOCKER_REGISTRY }}/${{ env.REPOSITORY }}:${{ env.DOCKER_TAG_PREFIX_EXCEPT_MAIN }}latest-arm64